KEYRING_SERVICE_NAME = "backmeup"
KEYRING_AWS_REGION_KEY = "backmeup-aws-region"
KEYRING_BACKUP_LOCATION_KEY = "backmeup-backup-location"
KEYRING_AWS_ACCESS_KEY = "backmeup-aws-access"
KEYRING_AWS_SECRET_KEY = "backmeup-aws-secret"
